[[seed]]
name = "Axelar team"
address = "3d67d0646cddcc203b41434aceea64ade22ba6fc@k8s-mainnet-axelarco-79b464ee93-f03cb16c57cf7cb2.elb.us-east-2.amazonaws.com:26656"

[[seed]]
name = "LunaNova"
address = "9c9b8eb8cad8648f31d3c9da3d14e825f11a7b52@public-seed.mainnet.axelar.lunanova.tech:26656"

[[seed]]
name = "Chainode"
address = "609504b517f88f628e98d4a918ffc69e9654b451@65.108.192.147:26656"

[[seed]]
name = "P-OPS Team"
address = "68cba02f45c0ecca62798861592fc8be5c228791@65.21.74.151:26656"
