[[seed]]
name = "Axelar team"
address = "2551bf072d23835e42a32921beacbf3425fe376f@k8s-mainnet-axelarco-3ab48adcdb-974f2bc59e735192.elb.us-east-2.amazonaws.com:26656"

[[seed]]
name = "LunaNova"
address = "9c9b8eb8cad8648f31d3c9da3d14e825f11a7b52@public-seed.mainnet.axelar.lunanova.tech:26656"

[[seed]]
name = "Chainode"
address = "609504b517f88f628e98d4a918ffc69e9654b451@65.108.192.147:26656"

[[seed]]
name = "P-OPS Team"
address = "691101434ca4016b28e6a9943da2ad6838b80685@axelar-seed.pops.one:26656"

[[seed]]
name = "Validatrium.com"
address = "44596cd8c8fd80be909a5968ac4ba6651d840b36@axelar-seed.validatrium.com:6969"

[[seed]]
name = "ContributionDAO"
address = "59df4b3832446cd0f9c369da01f2aa5fe9647248@135.181.220.61:15256"
